### ISSUE TITLE
🐛 Incorrect documentation for arbitrary git repo template links

### ISSUE THREAD

**Issue by paul121** [platformsh/platformsh-docs#2533]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/development/deploy-button.html

### What exactly should be updated?

The arbitrary git repository example does not work for creating projects from a template. It is unclear to me if the syntax for this arbitrary git repo template has changed or if a separate template file is always required now.

https://github.com/platformsh/platformsh-docs/blob/2820b6f5d6cdfb2e3c5bc20b8ba761d2d2f93d71/docs/src/development/deploy-button.md?plain=1#L63-L84

### Additional context

The example link that is provided gets a 400 error in the console UI:

https://console.platform.sh/org/create-project/?template=https://github.com/platformsh-templates/drupal8.git 

![Screenshot from 2022-09-06 22-12-33](https://user-images.githubusercontent.com/3116995/188793888-8d101344-52d4-4789-9d33-dd918c7ab2ce.png)

**Comment by CollierCZ** [comment]
Thanks for the report, @paul121! I know this is something that used to work. So I'll try looking into whether anything changed.

**Comment by CollierCZ** [comment]
It seems it was a bug and should be fixed soon.

**Comment by paul121** [comment]
Thanks @CollierCZ !

**Comment by CollierCZ** [comment]
It seems like this has been fixed even though the internal ticket for it is still open. At least, when I click the link in the description, it seems to work for me now.

**Comment by paul121** [comment]
Hmm I'm still getting the same error I posted above for this link: https://console.platform.sh/org/create-project/?template=https://github.com/platformsh-templates/drupal8.git

Are there maybe different versions of the frontend? I have this: Version v2.4.37+916c28f8d with  Platform.sh

**Comment by CollierCZ** [comment]
Oh, sorry, my mistake. The fix still hasn't been merged yet.

**Comment by CollierCZ** [comment]
It seems this has been fixed.
